---
- name: create tomcat group
  group:
    name: "{{tomcat_user_group}}"
    state: present

- name: create tomcat user
  user:
    name: "{{tomcat_user}}"
    group: "{{tomcat_user_group}}"
    home: "{{tomcat_home}}"
    shell: "/bin/false"
    state: present
    comment: "Tomcat user"

- name: create tomcat dest folder
  shell: mkdir -p "{{tomcat_dest}}"

- name: untar tomcat archive
  unarchive:
    src: "{{tomcat_targz}}"
    dest: "{{tomcat_dest}}"
    remote_src: yes

- name: remove ssl keystore
  file: path={{tomcat_home}}/conf/localhost-rsa.jks state=absent

- name: create ssl keystore
  command: keytool -genkey -noprompt -keyalg RSA -alias tomcat -dname "CN=localhost, OU=ID, O=EBI, L=Hinxton, S=Cambridge, C=UK" -validity 360 -keysize 2048 -keystore {{tomcat_home}}/conf/localhost-rsa.jks -storepass changeit -keypass changeit

- name: copy server.xml config
  template: src=server.xml dest={{tomcat_home}}/conf

- name: change permissions for tomcat_home
  shell: "{{item}}"
  args:
    chdir: "{{tomcat_home}}"
  with_items:
  - "chgrp -R {{tomcat_user_group}} conf"
  - "chgrp -R {{tomcat_user_group}} bin"
  - "chgrp -R {{tomcat_user_group}} lib"
  - "chmod g+rwx conf"
  - "chmod g+r conf/*"
  - "chown -R {{tomcat_user}} work/ temp/ logs/ webapps/"

- name: grep java_home
  shell: update-alternatives --query java | grep 'Value' | grep -o '/.*/jre'
  register: java_home_out

- set_fact:
    java_home: "{{java_home_out.stdout}}"

- name: copy tomcat.config
  template: src=tomcat.conf dest=/etc/init/tomcat.conf

- name: reload upstart configuration
  shell: initctl reload-configuration

- name: start tomcat
  shell: initctl start tomcat