- name: add jdk8 repository
  apt_repository:
    repo: 'ppa:webupd8team/java'
    state: present

- name: run apt-get update
  apt:
    update_cache: yes

- name: accepting oracle license
  shell: echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | debconf-set-selections

- name: install oracle jdk8
  apt: name={{item}} state=present
  with_items:
  - oracle-java8-installer